baseURL = "https://ybht.vercel.app"
title = "Petrel's Domain"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 20

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Petrel"
description = "我的个人博客"
keywords = "博客,技术,生活"
info = ["Ognuno si racconta la vita come gli fa più comodo."]
dateFormat = "2006-01-02"
since = 2025
colorScheme = "auto"
avatarURL = "images/avatar.png"
customCSS = ["css/custom.css"]

[taxonomies]
category = "categories"
tag = "tags"

[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[menu.main]]
name = "Contact me"
weight = 4
url = "contact/"

#[[params.social]]
#name = "Github"
#icon = "fa-brands fa-github fa-2x"
#weight = 1
#url = "https://github.com/Petrel0900/"

#[[params.social]]
#name = "Rednote"
#icon = "fa-brands fa-gitlab fa-2x"
#weight = 2
#url = "https://xiaohongshu.com/xxx/"

#[[params.social]]
#name = "Twitter"
#icon = "fa-brands fa-x-twitter fa-2x"
#weight = 3
#url = "https://twitter.com/xxx/"

#[[params.social]]
#name = "LinkedIn"
#icon = "fa-brands fa-linkedin fa-2x"
#weight = 4
#url = "https://www.linkedin.com/in/xxx/
